//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Url
    {
        public int id { get; set; }
        [Required]
        public string Title { get; set; }
        [Required]
        [Url]
        public string url { get; set; }
        [Required]
        public string urlDesc { get; set; }
        [Required]
        public int c_id { get; set; }
        public int u_id { get; set; }
        public string IsApproved { get; set; }
    
        public virtual tbl_Category tbl_Category { get; set; }
        public virtual tbl_User tbl_User { get; set; }
    }
}
